dbt_bigquery:
  outputs:
    dev:
      dataset: db_dbt_bigquery
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /home/srpantano/dbt-bigquery/dbt_bigquery/dbt-101.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-101-430700
      threads: 1
      type: bigquery
  target: dev

